# Generated by Django 4.2.7 on 2026-01-16 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('hire_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('rank', models.CharField(choices=[('professor', 'Professeur'), ('associate', 'Professeur Associé'), ('assistant', 'Assistant'), ('lecturer', 'Maître de Conférences')], max_length=50)),
                ('office_number', models.CharField(blank=True, max_length=20)),
                ('office_hours', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hire_date'],
            },
        ),
    ]
