# Generated by Django 4.2.7 on 2026-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Examen', 'verbose_name_plural': 'Examens'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date_recorded'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A - Excellent'), ('B', 'B - Bien'), ('C', 'C - Assez bien'), ('D', 'D - Passable'), ('F', 'F - Échec')], max_length=2, null=True),
        ),
    ]
