# Generated by Django 4.2.7 on 2026-01-18 00:40

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('tuition', 'Frais de scolarité'), ('exam_fee', "Frais d'examen"), ('library_fee', 'Frais de bibliothèque'), ('lab_fee', 'Frais de laboratoire'), ('scholarship', "Bourse d'études"), ('refund', 'Remboursement'), ('salary', 'Salaire enseignant'), ('maintenance', 'Maintenance'), ('equipment', 'Équipement'), ('other', 'Autre')], max_length=20)),
                ('category', models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense'), ('scholarship', 'Bourse'), ('salary', 'Salaire')], default='income', max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('paid_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Payé'), ('pending', 'En attente'), ('overdue', 'En retard'), ('cancelled', 'Annulé'), ('partial', 'Partiel')], default='pending', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('bank_transfer', 'Virement bancaire'), ('credit_card', 'Carte de crédit'), ('cash', 'Espèces'), ('check', 'Chèque'), ('mobile_payment', 'Paiement mobile')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_period', models.CharField(blank=True, choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_transactions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('year', models.IntegerField(default=2026)),
                ('base_salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('processing', 'En traitement'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Virement bancaire'), ('credit_card', 'Carte de crédit'), ('cash', 'Espèces'), ('check', 'Chèque'), ('mobile_payment', 'Paiement mobile')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='teachers.teacher')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payment', to='finance.transaction')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('first', 'Premier rappel'), ('second', 'Deuxième rappel'), ('final', 'Rappel final'), ('overdue', 'En retard')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.transaction')),
            ],
            options={
                'ordering': ['-reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'Texte'), ('number', 'Nombre'), ('boolean', 'Booléen'), ('json', 'JSON'), ('date', 'Date')], default='string', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['setting_key'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Journalier'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('total_salaries', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('total_scholarships', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('net_balance', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='financial_reports/')),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('engineering', "Faculté d'Ingénierie"), ('medicine', 'Faculté de Médecine'), ('sciences', 'Faculté des Sciences'), ('arts', 'Faculté des Arts'), ('economics', "Faculté d'Économie"), ('law', 'Faculté de Droit'), ('administration', 'Administration Générale'), ('it', 'Centre Informatique'), ('library', 'Bibliothèque Centrale'), ('student_affairs', 'Affaires Étudiantes'), ('maintenance', 'Maintenance'), ('salaries', 'Salaires')], max_length=50)),
                ('budget_type', models.CharField(choices=[('operational', 'Opérationnel'), ('capital', 'Capital'), ('salary', 'Salaires'), ('scholarship', 'Bourses'), ('development', 'Développement')], default='operational', max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('allocated_amount', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('spent_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('committed_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'department'],
                'unique_together': {('department', 'budget_type', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_number'], name='finance_tra_transac_137c49_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student', 'status'], name='finance_tra_student_ff08f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['teacher', 'status'], name='finance_tra_teacher_835bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='finance_tra_date_f21d66_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['due_date'], name='finance_tra_due_dat_f1aba6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('teacher', 'month', 'year')},
        ),
    ]
