# Generated by Django 4.2.7 on 2026-01-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_transaction_number'),
    ]

    operations = [
    ]
