# Generated by Django 4.2.7 on 2026-01-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_fix_schema'),
        ('finance', '0004_complete_schema'),
    ]

    operations = [
    ]
