# Generated by Django 4.2.7 on 2026-01-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_merge_0003_fix_schema_0004_complete_schema'),
    ]

    operations = [
    ]
