# Generated by Django 4.2.7 on 2026-01-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('credits', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('fall', 'Automne'), ('spring', 'Printemps'), ('summer', 'Été')], max_length=20)),
                ('academic_year', models.IntegerField()),
                ('max_students', models.IntegerField(default=30)),
                ('schedule', models.TextField(blank=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.teacher')),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('status', models.CharField(choices=[('enrolled', 'Inscrit'), ('completed', 'Terminé'), ('dropped', 'Abandonné')], default='enrolled', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
